bal]
    workgroup = WORKGROUP
    server string = FreeBSD Samba Server
    security = user

    log file = /var/log/samba4/log.%m
    max log size = 50
    map to guest = Bad User

[Share]
    comment = Public Share Folder
    path = /
    public = yes
    writable = yes
    printable = no
    guest ok = yes
    create mask = 0666
    directory mask = 0777

