#!/bin/sh


. /etc/rc.subr

name="xboxdrv"


load_rc_config $name




start_cmd="${name}_start"
stop_cmd="${name}_stop"

xboxdrv_start()
{
if [ ! -f /var/run/${name}.run ]
    then
 /usr/local/bin/screen -m -d   /usr/local/bin/xboxdrv -s &  echo $! > /var/run/${name}.run
  sleep 1
  chmod 0666 /dev/input/event10
 fi
 }
 xboxdrv_stop()
 {
 if [ -f /var/run/${name}.run ]
 then
 killall -INT $(echo -n 'ps aux | grep xboxdrv | grep "xboxdrv -s"') 2>>/var/log/${name}.log >>/var/log/${name}.log
 rm -f /var/run/${name}.run

 fi
   }
 run_rc_command "$1"
