#!/bin/sh


IP=$(
    arp-scan --localnet 2>/dev/null |
    awk '/NetApp/ { print $1; exit }'
)

if [ -z "$IP" ]; then
    echo "NetApp не найден"
    exit 1
fi

port="$(nc -z -v -w 1 $IP 3389  2>&1)"
port2="$(echo $port | grep succeeded)"

echo $port2

if [ -z "$port2" ]
then
     echo "\$var Пустая"
     zenity --info --text="виртуальная машина не запущена" --width=500
else
     echo "\$var не пустая"
     echo Y | xfreerdp /u:vcore  /p:639639 /w:1918 /h:1045  /v:$IP  /drive:home,/home/definitly  /sound /tls-seclevel:0 
fi


