#! /bin/sh

# PROVIDE: linuxbox
# BEFORE: netif
# REQUIRE: FILESYSTEMS sysctl kld
# KEYWORD: shutdown nojail suspend resume

. /etc/rc.subr

: ${linuxbox_enable="NO"}

name=linuxbox
desc="Manage linuxbox on boot, shutdown, suspend, and resume"
rcvar=linuxbox_enable
extra_commands="suspend resume fetch"

load_rc_config ${name}

command="/usr/local/sbin/${name}"
start_cmd="${command} start"
stop_cmd="${command} stop"
status_cmd="${command} status"
suspend_cmd="/usr/bin/true"
resume_cmd="${command} restart vmm"
fetch_cmd="${command} fetch"

run_rc_command "$1"
