#!/bin/sh
if test "$(id -u)" -ne 0; then
	printf "%s must be run as root\n" "${0##*/}"
	exit 1
fi

service linuxbox onedisable


var="$(grep -r "#pptdevs" /boot/loader.conf)"

if [ -z "$var" ]
then
     gsed -i 's/pptdevs=/#pptdevs=/' /boot/loader.conf
else
    
fi