#!/bin/sh
if test "$(id -u)" -ne 0; then
	printf "%s must be run as root\n" "${0##*/}"
	exit 1
fi

service winbox onedisable
service samba_server  onedisable

cp /usr/local/etc/winbox/loader.conf.linuxbox /boot/loader.conf