#!/bin/sh
if test "$(id -u)" -ne 0; then
	printf "%s must be run as root\n" "${0##*/}"
	exit 1
fi

if [ -z "$1" ]
then
     echo "не введен дистр "
     
else


fi

service winbox enable
cp /usr/local/etc/winbox/loader.conf.winbox /boot/loader.conf