#!/bin/sh

pkg=$@

install_16 () {

doas pkg install  -r myrepo16  -y  $pkg

}

install_15 () {

doas pkg install  -r myrepo15  -y  $pkg

}

stop_ipfw (){
doas service ipfw stop
doas killall -9 dvtws
}

start_ipfw (){
doas service ipfw start
}

stop_ipfw

if [ "15.0-STABLE" = "$(uname -r)"  ] || [ "15.1-BETA1" = "$(uname -r)"  ] ; then
    
    echo "install packages freebsd 15"
    install_15
else
    echo "install packages freebsd 16"
    install_16
fi

start_ipfw 