#!/bin/sh

pkg=$@

install_15 () {

doas pkg install  -r myrepo15  -y  $pkg

}

install_14 () {

doas pkg install  -r myrepo  -y  $pkg

}

stop_ipfw (){
doas service ipfw stop
doas killall -9 dvtws
}

start_ipfw (){
doas service ipfw start
}

stop_ipfw

if [ "14.3-STABLE" = "$(uname -r)"  ] || [ "14" = "$(uname -r)"  ] ; then
    
    echo "install packages freebsd 14"
    install_14
else
    echo "install packages freebsd 15"
    install_15
fi

start_ipfw 