#!/bin/sh
login=$(cat  ../../accounts/user | awk '{print $1}' |  head -n1)
proc=dtao
file=/home/$login/.config/labwc/rc.xml
file2=/home/$login/.config/labwc/rc.xml_new

   
                cat $file | sed 's/<top>0<\/top>/<top>14<\/top>/' > $file2
                mv $file2 $file
                labwc --reconfigure
          
          if ! [ -z $(pgrep $proc) ]
                then
                   killall -9 dtao
                   cat $file | sed 's/<top>14<\/top>/<top>0<\/top>/' > $file2
                   mv $file2 $file
                   labwc --reconfigure
          
                else
                    dtaoconky &
          fi
           