PidFile /tmp/clamd.pid
LocalSocket /home/definitly/.clamav-gui/clamd-socket
LogFile /home/definitly/.clamav-gui/clamd.log
LocalSocketGroup users
LogFileMaxSize 1M
OnAccessMaxFileSize 10M
OnAccessMaxThreads 10
OnAccessRetryAttempts 0
OnAccessExcludeUname root
OnAccessExcludeUID 0
OnAccessPrevention yes
OnAccessDenyOnError no
OnAccessExtraScanning yes
LogTime yes
LogSyslog no
LogFacility LOG_LOCAL6
LogRotate yes
ExtendedDetectionInfo yes
DatabaseDirectory /home/definitly/.clamav-gui/signatures
TCPAddr ::1
