#!/bin/sh

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi





if [ -z "$1" ]
then
  echo "Порядок использования: `basename $0` img  "
  exit 0
fi







mdconfig -a -t vnode -f $1 -u 0

mount  /dev/md0s2a /mnt
echo 'autoboot_delay="-1"' >> /mnt/boot/defaults/loader.conf
rm /mnt/etc/resolv.conf 
cp resolv.conf /mnt/etc
rm /mnt/etc/rc.local
cp rc.local /mnt/etc
cp zfs_install /mnt



umount /mnt
mdconfig -d -u 0



dd if=$1  of=/dev/da0 bs=64k