exec   setxkbmap -layout us,ru -option "grp:alt_shift_toggle,grp_led:scroll" -variant ",winkeys"  &  
firefox &
pcmanfm &
xterm -e screen &
feh --bg-scale ~/Downloads/1.jpg
while true; do
           xsetroot -name "cpu: $(top -bn 1 | grep "CPU:" | awk '{print $2 }' )  $( date +"%F %R" )"
           sleep 10    # Update time every minute
        done &

exec dwm