#!/bin/sh

# PROVIDE: ciadpi
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="ciadpi"
rcvar="ciadpi_enable"

command="/usr/local/bin/ciadpi"  # Убедитесь, что путь к ciadpi корректен
pidfile="/var/run/${name}.pid"

# Параметры запуска
ciadpi_flags="--ip 127.0.0.1 --debug 1 -p 8080 --hosts /home/definitly/whitelist --auto=none -Ku -a1 -An -o1 -At,r,s -d1"

# Используем daemon(8) для запуска в фоне и записи PID
procname="${command}"

load_rc_config $name
: ${ciadpi_enable:="NO"}

# Передаем аргументы напрямую через command_args
command_args="${ciadpi_flags} > /var/log/ciadpi.log 2>&1 &"

# Отключаем стандартный механизм pidfile, так как ciadpi не создаёт его автоматически
# Вместо этого используем background запуск через shell
start_cmd="${name}_start"
stop_cmd="${name}_stop"

ciadpi_start() {
	echo "Starting ${name}."
	/usr/sbin/daemon -f -p ${pidfile} ${command} ${ciadpi_flags}
}

ciadpi_stop() {
	if [ -f ${pidfile} ]; then
		echo "Stopping ${name}."
		kill `cat ${pidfile}`
		rm -f ${pidfile}
	else
		echo "${name} is not running."
	fi
}

run_rc_command "$1"