#!/bin/sh



 echo '#---- Generated by tint2conf 644d ----' >>   tint2rc
 echo '# See https://gitlab.com/o9000/tint2/wikis/Configure for' >>   tint2rc
 echo '# full documentation of the configuration options.' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Gradients' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Backgrounds' >>   tint2rc
 echo '# Background 1: Панель' >>   tint2rc
 echo 'rounded = 0' >>   tint2rc
 echo 'border_width = 1' >>   tint2rc
 echo 'border_sides = TBLR' >>   tint2rc
 echo 'border_content_tint_weight = 0' >>   tint2rc
 echo 'background_content_tint_weight = 0' >>   tint2rc
 echo 'background_color = #2d2d2d 100' >>   tint2rc
 echo 'border_color = #484848 100' >>   tint2rc
 echo 'background_color_hover = #2d2d2d 100' >>   tint2rc
 echo 'border_color_hover = #484848 100' >>   tint2rc
 echo 'background_color_pressed = #2d2d2d 100' >>   tint2rc
 echo 'border_color_pressed = #484848 100' >>   tint2rc
 echo '' >>   tint2rc
 echo '# Background 2: Активная задача, Всплывающий текст' >>   tint2rc
 echo 'rounded = 0' >>   tint2rc
 echo 'border_width = 0' >>   tint2rc
 echo 'border_sides = TBLR' >>   tint2rc
 echo 'border_content_tint_weight = 0' >>   tint2rc
 echo 'background_content_tint_weight = 0' >>   tint2rc
 echo 'background_color = #1c1c1c 100' >>   tint2rc
 echo 'border_color = #000000 100' >>   tint2rc
 echo 'background_color_hover = #1c1c1c 100' >>   tint2rc
 echo 'border_color_hover = #000000 100' >>   tint2rc
 echo 'background_color_pressed = #1c1c1c 100' >>   tint2rc
 echo 'border_color_pressed = #000000 100' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Panel' >>   tint2rc
 echo 'panel_items = LTSCPPP' >>   tint2rc
 echo 'panel_size = 104% 31' >>   tint2rc
 echo 'panel_margin = 0 0' >>   tint2rc
 echo 'panel_padding = 0 0 10' >>   tint2rc
 echo 'panel_background_id = 1' >>   tint2rc
 echo 'wm_menu = 1' >>   tint2rc
 echo 'panel_dock = 0' >>   tint2rc
 echo 'panel_pivot_struts = 0' >>   tint2rc
 echo 'panel_position = bottom center horizontal' >>   tint2rc
 echo 'panel_layer = bottom' >>   tint2rc
 echo 'panel_monitor = all' >>   tint2rc
 echo 'panel_shrink = 0' >>   tint2rc
 echo 'autohide = 0' >>   tint2rc
 echo 'autohide_show_timeout = 0.3' >>   tint2rc
 echo 'autohide_hide_timeout = 1.5' >>   tint2rc
 echo 'autohide_height = 6' >>   tint2rc
 echo 'strut_policy = follow_size' >>   tint2rc
 echo 'panel_window_name = tint2' >>   tint2rc
 echo 'disable_transparency = 0' >>   tint2rc
 echo 'mouse_effects = 0' >>   tint2rc
 echo 'font_shadow = 0' >>   tint2rc
 echo 'mouse_hover_icon_asb = 100 0 10' >>   tint2rc
 echo 'mouse_pressed_icon_asb = 100 0 0' >>   tint2rc
 echo 'scale_relative_to_dpi = 0' >>   tint2rc
 echo 'scale_relative_to_screen_height = 0' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Taskbar' >>   tint2rc
 echo 'taskbar_mode = single_desktop' >>   tint2rc
 echo 'taskbar_hide_if_empty = 0' >>   tint2rc
 echo 'taskbar_padding = 0 0 10' >>   tint2rc
 echo 'taskbar_background_id = 0' >>   tint2rc
 echo 'taskbar_active_background_id = 0' >>   tint2rc
 echo 'taskbar_name = 0' >>   tint2rc
 echo 'taskbar_hide_inactive_tasks = 0' >>   tint2rc
 echo 'taskbar_hide_different_monitor = 0' >>   tint2rc
 echo 'taskbar_hide_different_desktop = 0' >>   tint2rc
 echo 'taskbar_always_show_all_desktop_tasks = 0' >>   tint2rc
 echo 'taskbar_name_padding = 0 0' >>   tint2rc
 echo 'taskbar_name_background_id = 0' >>   tint2rc
 echo 'taskbar_name_active_background_id = 0' >>   tint2rc
 echo 'taskbar_name_font_color = #000000 100' >>   tint2rc
 echo 'taskbar_name_active_font_color = #000000 100' >>   tint2rc
 echo 'taskbar_distribute_size = 0' >>   tint2rc
 echo 'taskbar_sort_order = none' >>   tint2rc
 echo 'task_align = left' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Task' >>   tint2rc
 echo 'task_text = 1' >>   tint2rc
 echo 'task_icon = 1' >>   tint2rc
 echo 'task_centered = 0' >>   tint2rc
 echo 'urgent_nb_of_blink = 20' >>   tint2rc
 echo 'task_maximum_size = 200 32' >>   tint2rc
 echo 'task_padding = 10 4 10' >>   tint2rc
 echo 'task_font = Droid Sans 9' >>   tint2rc
 echo 'task_tooltip = 0' >>   tint2rc
 echo 'task_thumbnail = 0' >>   tint2rc
 echo 'task_thumbnail_size = 210' >>   tint2rc
 echo 'task_font_color = #dcdcdc 100' >>   tint2rc
 echo 'task_active_font_color = #ffffff 100' >>   tint2rc
 echo 'task_urgent_font_color = #ffffff 100' >>   tint2rc
 echo 'task_iconified_font_color = #dcdcdc 80' >>   tint2rc
 echo 'task_icon_asb = 100 0 0' >>   tint2rc
 echo 'task_active_icon_asb = 100 0 0' >>   tint2rc
 echo 'task_urgent_icon_asb = 100 0 0' >>   tint2rc
 echo 'task_iconified_icon_asb = 100 0 0' >>   tint2rc
 echo 'task_background_id = 0' >>   tint2rc
 echo 'task_active_background_id = 2' >>   tint2rc
 echo 'task_urgent_background_id = 0' >>   tint2rc
 echo 'task_iconified_background_id = 0' >>   tint2rc
 echo 'mouse_left = toggle_iconify' >>   tint2rc
 echo 'mouse_middle = none' >>   tint2rc
 echo 'mouse_right = close' >>   tint2rc
 echo 'mouse_scroll_up = toggle' >>   tint2rc
 echo 'mouse_scroll_down = iconify' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# System tray (notification area)' >>   tint2rc
 echo 'systray_padding = 0 6 15' >>   tint2rc
 echo 'systray_background_id = 0' >>   tint2rc
 echo 'systray_sort = left2right' >>   tint2rc
 echo 'systray_icon_size = 16' >>   tint2rc
 echo 'systray_icon_asb = 100 0 0' >>   tint2rc
 echo 'systray_monitor = primary' >>   tint2rc
 echo 'systray_name_filter =' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Launcher' >>   tint2rc
 echo 'launcher_padding = 0 0 0' >>   tint2rc
 echo 'launcher_background_id = 0' >>   tint2rc
 echo 'launcher_icon_background_id = 0' >>   tint2rc
 echo 'launcher_icon_size = 0' >>   tint2rc
 echo 'launcher_icon_asb = 100 0 0' >>   tint2rc
 echo 'launcher_icon_theme_override = 0' >>   tint2rc
 echo 'startup_notifications = 0' >>   tint2rc
 echo 'launcher_tooltip = 0' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Clock' >>   tint2rc
 echo 'time1_format = %H:%M' >>   tint2rc
 echo 'time2_format =' >>   tint2rc
 echo 'time1_font = Droid Sans 9' >>   tint2rc
 echo 'time1_timezone =' >>   tint2rc
 echo 'time2_timezone =' >>   tint2rc
 echo 'clock_font_color = #dcdcdc 100' >>   tint2rc
 echo 'clock_padding = 10 6' >>   tint2rc
 echo 'clock_background_id = 0' >>   tint2rc
 echo 'clock_tooltip =' >>   tint2rc
 echo 'clock_tooltip_timezone =' >>   tint2rc
 echo 'clock_lclick_command = gsimplecal' >>   tint2rc
 echo 'clock_rclick_command =' >>   tint2rc
 echo 'clock_mclick_command =' >>   tint2rc
 echo 'clock_uwheel_command =' >>   tint2rc
 echo 'clock_dwheel_command =' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Battery' >>   tint2rc
 echo 'battery_tooltip = 1' >>   tint2rc
 echo 'battery_low_status = 20' >>   tint2rc
 echo 'battery_low_cmd = notify-send "battery low"' >>   tint2rc
 echo 'battery_full_cmd =' >>   tint2rc
 echo 'bat1_font = Liberation Mono 8' >>   tint2rc
 echo 'bat2_font = Liberation Mono 8' >>   tint2rc
 echo 'battery_font_color = #b5b5b5 100' >>   tint2rc
 echo 'bat1_format =' >>   tint2rc
 echo 'bat2_format =' >>   tint2rc
 echo 'battery_padding = 2 0' >>   tint2rc
 echo 'battery_background_id = 0' >>   tint2rc
 echo 'battery_hide = 96' >>   tint2rc
 echo 'battery_lclick_command =' >>   tint2rc
 echo 'battery_rclick_command =' >>   tint2rc
 echo 'battery_mclick_command =' >>   tint2rc
 echo 'battery_uwheel_command =' >>   tint2rc
 echo 'battery_dwheel_command =' >>   tint2rc
 echo 'ac_connected_cmd =' >>   tint2rc
 echo 'ac_disconnected_cmd =' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Button 1' >>   tint2rc
 echo 'button = new' >>   tint2rc
 echo 'button_icon = ~/.config/icons/docker.png' >>   tint2rc
 echo 'button_text =' >>   tint2rc
 echo 'button_tooltip = Start/Stop VPN' >>   tint2rc
 echo 'button_lclick_command = dockerbox.py' >>   tint2rc
 echo 'button_rclick_command =' >>   tint2rc
 echo 'button_mclick_command =' >>   tint2rc
 echo 'button_uwheel_command =' >>   tint2rc
 echo 'button_dwheel_command =' >>   tint2rc
 echo 'button_font_color = #ffffff 100' >>   tint2rc
 echo 'button_padding = 2 2' >>   tint2rc
 echo 'button_background_id = 0' >>   tint2rc
 echo 'button_centered = 1' >>   tint2rc
 echo 'button_max_icon_size = 28' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Button 2' >>   tint2rc
 echo 'button = new' >>   tint2rc
 echo 'button_icon = ~/.config/icons/shutdown.png' >>   tint2rc
 echo 'button_text =' >>   tint2rc
 echo 'button_tooltip = shutdown' >>   tint2rc
 echo 'button_lclick_command = powerpy' >>   tint2rc
 echo 'button_rclick_command =' >>   tint2rc
 echo 'button_mclick_command =' >>   tint2rc
 echo 'button_uwheel_command =' >>   tint2rc
 echo 'button_dwheel_command =' >>   tint2rc
 echo 'button_font_color = #000000 100' >>   tint2rc
 echo 'button_padding = 0 0' >>   tint2rc
 echo 'button_background_id = 0' >>   tint2rc
 echo 'button_centered = 0' >>   tint2rc
 echo 'button_max_icon_size = 0' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Button 3' >>   tint2rc
 echo 'button = new' >>   tint2rc
 echo 'button_icon = ~/.config/icons/ubuntu.png' >>   tint2rc
 echo 'button_text =' >>   tint2rc
 echo 'button_tooltip = ubuntu_chroot' >>   tint2rc
 echo 'button_lclick_command = ubuntu_chroot' >>   tint2rc
 echo 'button_rclick_command =' >>   tint2rc
 echo 'button_mclick_command =' >>   tint2rc
 echo 'button_uwheel_command =' >>   tint2rc
 echo 'button_dwheel_command =' >>   tint2rc
 echo 'button_font_color = #000000 100' >>   tint2rc
 echo 'button_padding = 2 2' >>   tint2rc
 echo 'button_background_id = 0' >>   tint2rc
 echo 'button_centered = 1' >>   tint2rc
 echo 'button_max_icon_size = 28' >>   tint2rc
 echo '' >>   tint2rc
 echo '#-------------------------------------' >>   tint2rc
 echo '# Tooltip' >>   tint2rc
 echo 'tooltip_show_timeout = 0' >>   tint2rc
 echo 'tooltip_hide_timeout = 0' >>   tint2rc
 echo 'tooltip_padding = 2 2' >>   tint2rc
 echo 'tooltip_background_id = 2' >>   tint2rc
 echo 'tooltip_font_color = #ffffff 100' >>   tint2rc
 echo 'tooltip_font = Droid Sans 9' >>   tint2rc
 echo '' >>   tint2rc


