#!/bin/sh
proc=tint2
        
        if ! [ -z $(pgrep -u $(whoami) $proc) ]
                then
                   killall -9 tint2
                   killall -9 xxkb
                else
                    tint2 &
                    xxkb &
        fi
           