login=$(cat  ../accounts/user | awk '{print $1}' |  head -n1)
 
 echo '#---- Generated by tint2conf 644d ----' >> /home/$login/.config/tint2/tint2rc
 echo '# See https://gitlab.com/o9000/tint2/wikis/Configure for' >> /home/$login/.config/tint2/tint2rc
 echo '# full documentation of the configuration options.' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Gradients' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Backgrounds' >> /home/$login/.config/tint2/tint2rc
 echo '# Background 1: Панель' >> /home/$login/.config/tint2/tint2rc
 echo 'rounded = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'border_width = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'border_sides = TBLR' >> /home/$login/.config/tint2/tint2rc
 echo 'border_content_tint_weight = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'background_content_tint_weight = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'background_color = #2d2d2d 100' >> /home/$login/.config/tint2/tint2rc
 echo 'border_color = #484848 100' >> /home/$login/.config/tint2/tint2rc
 echo 'background_color_hover = #2d2d2d 100' >> /home/$login/.config/tint2/tint2rc
 echo 'border_color_hover = #484848 100' >> /home/$login/.config/tint2/tint2rc
 echo 'background_color_pressed = #2d2d2d 100' >> /home/$login/.config/tint2/tint2rc
 echo 'border_color_pressed = #484848 100' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '# Background 2: Активная задача, Всплывающий текст' >> /home/$login/.config/tint2/tint2rc
 echo 'rounded = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'border_width = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'border_sides = TBLR' >> /home/$login/.config/tint2/tint2rc
 echo 'border_content_tint_weight = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'background_content_tint_weight = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'background_color = #1c1c1c 100' >> /home/$login/.config/tint2/tint2rc
 echo 'border_color = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo 'background_color_hover = #1c1c1c 100' >> /home/$login/.config/tint2/tint2rc
 echo 'border_color_hover = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo 'background_color_pressed = #1c1c1c 100' >> /home/$login/.config/tint2/tint2rc
 echo 'border_color_pressed = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Panel' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_items = LTSCPPP' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_size = 104% 31' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_margin = 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_padding = 0 0 10' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_background_id = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'wm_menu = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_dock = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_pivot_struts = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_position = bottom center horizontal' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_layer = bottom' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_monitor = all' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_shrink = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'autohide = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'autohide_show_timeout = 0.3' >> /home/$login/.config/tint2/tint2rc
 echo 'autohide_hide_timeout = 1.5' >> /home/$login/.config/tint2/tint2rc
 echo 'autohide_height = 6' >> /home/$login/.config/tint2/tint2rc
 echo 'strut_policy = follow_size' >> /home/$login/.config/tint2/tint2rc
 echo 'panel_window_name = tint2' >> /home/$login/.config/tint2/tint2rc
 echo 'disable_transparency = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_effects = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'font_shadow = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_hover_icon_asb = 100 0 10' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_pressed_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'scale_relative_to_dpi = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'scale_relative_to_screen_height = 0' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Taskbar' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_mode = single_desktop' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_hide_if_empty = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_padding = 0 0 10' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_active_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_name = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_hide_inactive_tasks = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_hide_different_monitor = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_hide_different_desktop = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_always_show_all_desktop_tasks = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_name_padding = 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_name_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_name_active_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_name_font_color = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_name_active_font_color = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_distribute_size = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'taskbar_sort_order = none' >> /home/$login/.config/tint2/tint2rc
 echo 'task_align = left' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Task' >> /home/$login/.config/tint2/tint2rc
 echo 'task_text = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'task_icon = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'task_centered = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'urgent_nb_of_blink = 20' >> /home/$login/.config/tint2/tint2rc
 echo 'task_maximum_size = 200 32' >> /home/$login/.config/tint2/tint2rc
 echo 'task_padding = 10 4 10' >> /home/$login/.config/tint2/tint2rc
 echo 'task_font = Droid Sans 9' >> /home/$login/.config/tint2/tint2rc
 echo 'task_tooltip = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_thumbnail = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_thumbnail_size = 210' >> /home/$login/.config/tint2/tint2rc
 echo 'task_font_color = #dcdcdc 100' >> /home/$login/.config/tint2/tint2rc
 echo 'task_active_font_color = #ffffff 100' >> /home/$login/.config/tint2/tint2rc
 echo 'task_urgent_font_color = #ffffff 100' >> /home/$login/.config/tint2/tint2rc
 echo 'task_iconified_font_color = #dcdcdc 80' >> /home/$login/.config/tint2/tint2rc
 echo 'task_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_active_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_urgent_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_iconified_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_active_background_id = 2' >> /home/$login/.config/tint2/tint2rc
 echo 'task_urgent_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'task_iconified_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_left = toggle_iconify' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_middle = none' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_right = close' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_scroll_up = toggle' >> /home/$login/.config/tint2/tint2rc
 echo 'mouse_scroll_down = iconify' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# System tray (notification area)' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_padding = 0 6 15' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_sort = left2right' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_icon_size = 16' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_monitor = primary' >> /home/$login/.config/tint2/tint2rc
 echo 'systray_name_filter =' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Launcher' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_padding = 0 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_icon_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_icon_size = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_icon_asb = 100 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_icon_theme_override = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'startup_notifications = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'launcher_tooltip = 0' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Clock' >> /home/$login/.config/tint2/tint2rc
 echo 'time1_format = %H:%M' >> /home/$login/.config/tint2/tint2rc
 echo 'time2_format =' >> /home/$login/.config/tint2/tint2rc
 echo 'time1_font = Droid Sans 9' >> /home/$login/.config/tint2/tint2rc
 echo 'time1_timezone =' >> /home/$login/.config/tint2/tint2rc
 echo 'time2_timezone =' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_font_color = #dcdcdc 100' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_padding = 10 6' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_tooltip =' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_tooltip_timezone =' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_lclick_command = gsimplecal' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_rclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_mclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_uwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'clock_dwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Battery' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_tooltip = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_low_status = 20' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_low_cmd = notify-send "battery low"' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_full_cmd =' >> /home/$login/.config/tint2/tint2rc
 echo 'bat1_font = Liberation Mono 8' >> /home/$login/.config/tint2/tint2rc
 echo 'bat2_font = Liberation Mono 8' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_font_color = #b5b5b5 100' >> /home/$login/.config/tint2/tint2rc
 echo 'bat1_format =' >> /home/$login/.config/tint2/tint2rc
 echo 'bat2_format =' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_padding = 2 0' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_hide = 96' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_lclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_rclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_mclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_uwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'battery_dwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'ac_connected_cmd =' >> /home/$login/.config/tint2/tint2rc
 echo 'ac_disconnected_cmd =' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Button 1' >> /home/$login/.config/tint2/tint2rc
 echo 'button = new' >> /home/$login/.config/tint2/tint2rc
 echo 'button_icon = /home/definitly/.config/icons/docker.png' >> /home/$login/.config/tint2/tint2rc
 echo 'button_text =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_tooltip = Start/Stop VPN' >> /home/$login/.config/tint2/tint2rc
 echo 'button_lclick_command = dockerbox.py' >> /home/$login/.config/tint2/tint2rc
 echo 'button_rclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_mclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_uwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_dwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_font_color = #ffffff 100' >> /home/$login/.config/tint2/tint2rc
 echo 'button_padding = 2 2' >> /home/$login/.config/tint2/tint2rc
 echo 'button_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'button_centered = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'button_max_icon_size = 28' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Button 2' >> /home/$login/.config/tint2/tint2rc
 echo 'button = new' >> /home/$login/.config/tint2/tint2rc
 echo 'button_icon = /home/definitly/.config/icons/shutdown.png' >> /home/$login/.config/tint2/tint2rc
 echo 'button_text =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_tooltip = shutdown' >> /home/$login/.config/tint2/tint2rc
 echo 'button_lclick_command = powerpy' >> /home/$login/.config/tint2/tint2rc
 echo 'button_rclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_mclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_uwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_dwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_font_color = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo 'button_padding = 0 0' >> /home/$login/.config/tint2/tint2rc
 echo 'button_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'button_centered = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'button_max_icon_size = 0' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Button 3' >> /home/$login/.config/tint2/tint2rc
 echo 'button = new' >> /home/$login/.config/tint2/tint2rc
 echo 'button_icon = /home/definitly/.config/icons/ubuntu.png' >> /home/$login/.config/tint2/tint2rc
 echo 'button_text =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_tooltip = ubuntu_chroot' >> /home/$login/.config/tint2/tint2rc
 echo 'button_lclick_command = ubuntu_chroot' >> /home/$login/.config/tint2/tint2rc
 echo 'button_rclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_mclick_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_uwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_dwheel_command =' >> /home/$login/.config/tint2/tint2rc
 echo 'button_font_color = #000000 100' >> /home/$login/.config/tint2/tint2rc
 echo 'button_padding = 2 2' >> /home/$login/.config/tint2/tint2rc
 echo 'button_background_id = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'button_centered = 1' >> /home/$login/.config/tint2/tint2rc
 echo 'button_max_icon_size = 28' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
 echo '#-------------------------------------' >> /home/$login/.config/tint2/tint2rc
 echo '# Tooltip' >> /home/$login/.config/tint2/tint2rc
 echo 'tooltip_show_timeout = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'tooltip_hide_timeout = 0' >> /home/$login/.config/tint2/tint2rc
 echo 'tooltip_padding = 2 2' >> /home/$login/.config/tint2/tint2rc
 echo 'tooltip_background_id = 2' >> /home/$login/.config/tint2/tint2rc
 echo 'tooltip_font_color = #ffffff 100' >> /home/$login/.config/tint2/tint2rc
 echo 'tooltip_font = Droid Sans 9' >> /home/$login/.config/tint2/tint2rc
 echo '' >> /home/$login/.config/tint2/tint2rc
